// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";  this.TestCommand = Backbone.Model.extend({
    'defaults': {
      'name': '',
      'value': '',
      'selector': '',
      'selected': false
    }
  });

}).call(this);
