// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";
  var checkEvent, getSelector, sendMessage;

  getSelector = function(elem, selector) {
    var child, i, parent, _i, _len, _ref;

    if (selector == null) {
      selector = '';
    }
    if (elem.tagName.toLowerCase() === 'body') {
      return 'body ' + selector;
    }
    parent = elem.parentElement;
    if (!parent) {
      return selector;
    }
    _ref = parent.children;
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      child = _ref[i];
      if (child !== elem) {
        continue;
      }
      selector = ">*:nth-child(" + (i + 1) + ")" + selector;
      break;
    }
    return getSelector(parent, selector);
  };

  sendMessage = function(param) {
    var key, message, val;

    message = {};
    for (key in param) {
      val = param[key];
      message[key] = val;
    }
    message['command'] = 'event';
    message['orign'] = location.origin;
    return chrome.extension.sendMessage(message);
  };

  checkEvent = {
    'click': function(elem) {
      var tag;

      tag = elem.tagName.toLocaleLowerCase();
      if (tag === 'a') {
        return true;
      }
      if (tag === 'button') {
        return true;
      }
      if (tag !== 'input') {
        return false;
      }
      if (elem.type === 'text') {
        return false;
      }
      if (elem.type === 'password') {
        return false;
      }
      return true;
    },
    'change': function(elem) {
      var tag;

      tag = elem.tagName.toLocaleLowerCase();
      if (tag === 'textarea') {
        return true;
      }
      if (tag === 'select') {
        return true;
      }
      if (tag !== 'input') {
        return false;
      }
      if (elem.type === 'text') {
        return true;
      }
      if (elem.type === 'password') {
        return true;
      }
      return false;
    }
  };

  window.addEventListener('click', function(evn) {
    var elem;

    elem = evn.srcElement;
    if (!checkEvent['click'](elem)) {
      return;
    }
    return sendMessage({
      'name': 'click',
      'selector': getSelector(elem)
    });
  });

  window.addEventListener('change', function(evn) {
    var elem;

    elem = evn.srcElement;
    if (!checkEvent['change'](elem)) {
      return;
    }
    return sendMessage({
      'name': 'text',
      'value': elem.value,
      'selector': getSelector(elem)
    });
  });

}).call(this);
