// Generated by CoffeeScript 1.6.2
(function() {
  var _this = this;

  (function() {
    "use strict";
    var getSelector, name, _i, _len, _ref, _results;

    getSelector = function(elem, selector) {
      var child, i, parent, _i, _len, _ref;

      parent = elem.parentElement;
      if (!parent) {
        return selector;
      }
      _ref = parent.children;
      for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
        child = _ref[i];
        if (child !== elem) {
          continue;
        }
        selector = "*:nth-child(" + (i + 1) + ") " + selector;
        break;
      }
      return getSelector(parent, selector);
    };
    _ref = ['click', 'blur'];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      name = _ref[_i];
      _results.push(_this.addEventListener(name, function(evn) {
        var selector;

        selector = getSelector(evn.srcElement);
        return chrome.extension.sendMessage({
          'command': 'event',
          'name': evn.type,
          'selector': selector
        });
      }));
    }
    return _results;
  })();

}).call(this);
