// Generated by CoffeeScript 1.6.2
(function() {
  var _this = this;

  (function() {
    var controllers, global, mod, name, _i, _len;

    global = _this;
    "use strict";
    controllers = ['menuPanelCtrl', 'testCaseCtrl', 'testCommandCtrl', 'messagesCtrl'];
    mod = angular.module('ng');
    for (_i = 0, _len = controllers.length; _i < _len; _i++) {
      name = controllers[_i];
      mod.controller(name, ['$scope', global[name]]);
    }
    return _this.addEventListener('DOMContentLoaded', function() {
      var scopes, _j, _len1;

      scopes = {};
      for (_j = 0, _len1 = controllers.length; _j < _len1; _j++) {
        name = controllers[_j];
        scopes[name] = angular.element(document.querySelector('[ng-controller="' + name + '"]')).scope();
      }
      return chrome.extension.onMessage.addListener(function(msg) {
        if (msg.command !== 'event') {
          return;
        }
        delete msg.command;
        return scopes['testCommandCtrl'].add(msg);
      });
    });
  })();

}).call(this);
