// Generated by CoffeeScript 1.6.2
(function() {
  var _this = this;

  (function() {
    "use strict";
    var global;

    global = _this;
    global.scopes = {};
    Deferred.onerror = function() {
      return console.debug(arguments);
    };
    global.selenium = new SeleniumIDE();
    global.selenium.init();
    return document.addEventListener('DOMContentLoaded', function() {
      var elem, mod, name, _i, _len, _ref;

      mod = angular.module('ng');
      _ref = document.querySelectorAll('[ng-controller]');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        elem = _ref[_i];
        name = elem.getAttribute('ng-controller');
        mod.controller(name, ['$scope', global[name]]);
        global.scopes[name] = angular.element(elem).scope();
      }
      return global.addEventListener('DOMContentLoaded', function() {
        return chrome.extension.onMessage.addListener(function(msg) {
          if (msg.command !== 'event') {
            return;
          }
          delete msg.command;
          return global.scopes['testCommandCtrl'].add(msg);
        });
      });
    });
  })();

}).call(this);
