// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";
  var _this = this;

  (function() {
    var create_window;

    create_window = function() {
      var _this = this;

      return chrome.windows.create({
        'url': '/html/panel.html',
        'type': 'panel',
        'focused': false,
        'top': 0,
        'left': 0,
        'height': 500,
        'width': 300
      }, function(win) {
        return localStorage.window_id = win.id;
      });
    };
    if (localStorage.window_id) {
      return chrome.windows.get(localStorage.window_id | 0, function(win) {
        if (win) {
          return chrome.windows.update(win.id, {
            'focused': true
          });
        } else {
          return create_window();
        }
      });
    } else {
      return create_window();
    }
  })();

}).call(this);
