// Generated by CoffeeScript 1.6.2
(function() {
  chrome.windows.create({
    'url': '/src/panel/index.html',
    'type': 'panel',
    'focused': false,
    'top': 0,
    'left': 0,
    'height': 500,
    'width': 300
  });

}).call(this);
