// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";
  var _this = this;

  (function() {
    _this.expect = chai.expect;
    mocha.globals(['setTimeout', 'setInterval', 'clearTimeout', 'clearInterval', 'XMLHttpRequest']);
    Deferred.next = Deferred.next_default;
    _this.mocha.sinon = {};
    _this.mocha.sinon.testBefore = function(callback) {
      return function() {
        this.sandbox = sinon.sandbox.create();
        this.sandbox.useFakeServer();
        this.sandbox.useFakeTimers();
        return callback.apply(this, arguments);
      };
    };
    _this.mocha.sinon.testAfter = function(callback) {
      return function() {
        this.sandbox.verifyAndRestore();
        return callback.apply(this, arguments);
      };
    };
    if ('undefined' !== typeof console) {
      sinon.log = function() {};
    }
    return Deferred.onerror = function(e) {
      throw e;
    };
  })();

}).call(this);
