// Generated by CoffeeScript 1.6.2
(function() {
  describe('SeleniumIDE', function() {
    beforeEach(function() {
      return this.sel = new SeleniumIDE;
    });
    return it('getSessionId', mocha.sinon.test(function() {
      this.sel.init();
      this.sel.getSessionId();
      expect(this.sandbox.requests).to.equal(1);
      return this.sandbox.requests[0].respond;
    }));
  });

}).call(this);
