// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";  this.menuPanelCtrl = function($scope) {
    $scope.operationRecording = true;
    $scope.operationSpeed = 0;
    $scope.executeTestCase = function() {
      var tests;

      tests = scopes['testCommandCtrl'].getTestCase();
      if (!tests.length) {
        return;
      }
      if (!$scope.baseURL) {
        return;
      }
      return selenium.send({
        'baseURL': $scope.baseURL,
        'tests': tests
      });
    };
    $scope.changeOperationSpeed = function() {
      return selenium.setSpeed($scope.operationSpeed);
    };
    $scope.quitBrowser = function() {
      return selenium.quit();
    };
    return this;
  };

}).call(this);
