// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";  this.testCommandCtrl = function($scope) {
    $scope.testCase = new TestCase();
    $scope.testCase.add([
      {
        'name': 'text',
        'value': 'value',
        'selector': 'selectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselectorselector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }, {
        'name': 'text',
        'value': 'value',
        'selector': 'selector'
      }
    ]);
    $scope.commandList = [
      {
        'value': 'text',
        'text': 'text'
      }, {
        'value': 'click',
        'text': 'click'
      }
    ];
    $scope.selectedCommand = void 0;
    $scope.add = function(command) {
      var wrap;

      $scope.testCase.push(command);
      $scope.$apply();
      wrap = document.querySelector('[ng-controller="testCommandCtrl"] .commandsWrap');
      return wrap.scrollTop = wrap.scrollHeight;
    };
    $scope.selectLine = function(command) {
      var sel, _i, _len, _ref;

      _ref = $scope.testCase.where({
        'selected': true
      });
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        sel = _ref[_i];
        sel.set('selected', false);
      }
      command.set('selected', true);
      return $scope.selectedCommand = command;
    };
    $scope.getTestCase = function() {
      var cmd, cmds;

      cmds = (function() {
        var _i, _len, _ref, _results;

        _ref = $scope.testCase.toArray();
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          cmd = _ref[_i];
          _results.push(cmd.attributes);
        }
        return _results;
      })();
      return cmds;
    };
    $scope.$on('click', function() {
      var sel, _i, _len, _ref;

      _ref = $scope.testCase.where({
        'selected': true
      });
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        sel = _ref[_i];
        sel.set('selected', false);
      }
      return $scope.$apply();
    });
    return this;
  };

}).call(this);
